09_SolucionMVC_Autenticacion/AplicacionMVC_Autenticacion/Controllers/RolesController.cs
using AplicacionMVC_Autenticacion.Models;
using AplicacionMVC_Autenticacion.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AplicacionMVC_Autenticacion.Controllers
{
    public class RolesController : Controller
    {
        // CRUD Tabla de AspNetRoles
        private RoleManager<IdentityRole> gestorRoles = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
        
        // GET: Roles
        public ActionResult Index()
        {
            return View(gestorRoles.Roles.Select(rol => new RolViewModel { Id = rol.Id, Nombre = rol.Name }));
        }

        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(RolViewModel rolViewModel)
        {
            if (ModelState.IsValid)
            {
                if (!gestorRoles.RoleExists(rolViewModel.Nombre))
                {
                    gestorRoles.Create(new IdentityRole(rolViewModel.Nombre));
                }

                return RedirectToAction("Index");
            }

            return View(rolViewModel);
        }
    }
}

09_SolucionMVC_Autenticacion/AplicacionMVC_Autenticacion/Controllers/UsuariosController.cs
using AplicacionMVC_Autenticacion.Models;
using AplicacionMVC_Autenticacion.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AplicacionMVC_Autenticacion.Controllers
{
    public class UsuariosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> gestorUsuarios = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

        // GET: Usuarios
        public ActionResult Index()
        {
            return View(gestorUsuarios.Users.Select(u => new UserViewModel { Email = u.Email, Nombre = u.UserName, Id = u.Id }));
        }

        public ActionResult Roles(string id)
        {
            UserViewModel userViewModel = CargarInformacion(id);
            return View(userViewModel);
        }

        public ActionResult AgregarRol(string userId)
        {
            if (String.IsNullOrEmpty(userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.Users.Find(userId);

            if (user == null)
            {
                return HttpNotFound();
            }

            UserViewModel userViewModel = new UserViewModel
            {
                Id = user.Id,
                Nombre = user.UserName,
                Email = user.Email
            };

            ViewBag.RolId = new SelectList(db.Roles.OrderBy(r => r.Name), "Id", "Name");

            return View(userViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarRol(UserViewModel userViewModel)
        {
            string rolId = Request["RolId"];

            if (string.IsNullOrEmpty(rolId))
            {
                ViewBag.RolId = new SelectList(db.Roles.OrderBy(r => r.Name), "Id", "Name");
                return View(userViewModel);
            }

            var rol = db.Roles.Find(rolId);

            if (!gestorUsuarios.IsInRole(userViewModel.Id, rol.Name))
            {
                gestorUsuarios.AddToRole(userViewModel.Id, rol.Name);
            }

            userViewModel = CargarInformacion(userViewModel.Id);
            return View("Roles", userViewModel);
        }

        private UserViewModel CargarInformacion(string userId)
        {
            // AspNetUsers y AspNetRoles

            // Obtener información del usuario, creamos un objeto ViewModel para la View
            var usuario = db.Users.Find(userId);

            if (usuario == null) return null;

            UserViewModel userViewModel = new UserViewModel
            {
                Id = usuario.Id,
                Nombre = usuario.UserName,
                Email = usuario.Email,
                Roles = new List<RolViewModel>()
            };

            // Obtener información del rol, especificamente el nombre del rol
            foreach (var role in usuario.Roles)
            {
                var rol = db.Roles.Find(role.RoleId);

                RolViewModel rolViewModel = new RolViewModel
                {
                    Id = role.RoleId,
                    Nombre = rol.Name
                };

                userViewModel.Roles.Add(rolViewModel);
            }

            return userViewModel;
        }
    }
}

09_SolucionMVC_Autenticacion/AplicacionMVC_Autenticacion/Views/Usuarios/AgregarRol.cshtml
@model AplicacionMVC_Autenticacion.ViewModels.UserViewModel

@{
    ViewBag.Title = "AgregarRol";
}

<h2>Agregar rol a @Model.Nombre</h2>

@using (Html.BeginForm("AgregarRol", "Usuarios", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RolId", null, "-- Seleccione un rol --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar rol" class="btn btn-dark" />
                @Html.ActionLink("Retornar al usuario", "Roles", new { id = Model.Id }, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}

09_SolucionMVC_Autenticacion/AplicacionMVC_Autenticacion/Views/Usuarios/Index.cshtml
@model IEnumerable<AplicacionMVC_Autenticacion.ViewModels.UserViewModel> 

@{
    ViewBag.Title = "Index";
}

<h2>Usuarios</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
                &nbsp;
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
                &nbsp;
            </td>
            <td>
                @Html.ActionLink("Roles", "Roles", new { id = item.Id })
            </td>
        </tr>
    }

</table>

09_SolucionMVC_Autenticacion/AplicacionMVC_Autenticacion/Views/Usuarios/Roles.cshtml
@model AplicacionMVC_Autenticacion.ViewModels.UserViewModel

@{
    ViewBag.Title = "Roles";
}

<h2>Roles del usuario @Model.Nombre</h2>

<p>
    @Html.ActionLink("Agregar rol", "AgregarRol", new { UserId = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Retonar", "Index", "Usuarios", null, new { @class = "btn btn-info" })
</p>

<table class="table">
    <tr>
        <th>
            Rol
        </th>
    </tr>
    @foreach (var item in Model.Roles)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
        </tr>
    }

</table>